name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Go 1.16 setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.0
        
      - name: Run 
        run: cd Zad3 && go build server.go
